### ISSUE TITLE
Error: Option not valid for Pure Cool Link Air Quality

### ISSUE THREAD

**Issue by kwbeck** [shenxn/ha-dyson#108]
I'm seeing this error about once a day, no matter which Air Quality setting is selected.

Installed version of the integration is v0.16.2

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/select/__init__.py:53
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:55:26 (1 occurrences)
Last logged: 20:55:26

[547814224272] Option not valid for Pure Cool Link Air Quality
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 53, in async_select_option
    raise ValueError(f"Option {option} not valid for {entity.name}")
ValueError: Option  not valid for Pure Cool Link Air Quality

```

System config info is:

## System Health

version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4995
Installed Version | 1.23.0
Stage | running
Available Repositories | 1077
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 7, 2023, 19:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 232.2 GB
disk_used | 14.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS to MQTT (0.36.0), Home Assistant Google Drive Backup (0.105.2), File editor (5.3.3), ArgonOne Active Cooling (24.1), Samba share (9.5.1), Terminal & SSH (9.3.0)

</details>

**Comment by Kakise** [comment]
Fixed in last update, 0.16.3
