### ISSUE TITLE
"Error adding entities for domain switch with platform dyson_local" with HA 2022.4.0

### ISSUE THREAD

**Issue by rkallensee** [shenxn/ha-dyson#114]
After upgrading to HA 2022.4.0, the "night mode" and "continuous monitoring" switches of my Dyson Pure Cool in Home Assistant stopped working, and in the logs I can see the error `Error adding entities for domain switch with platform dyson_local` and the following traceback:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

Additionally I'm now seeing the error `Error adding entities for domain sensor with platform dyson_local` and the temperature sensor stopped working as well, but I assume this was fixed already in c777eb8ba7d28c468293e59f304e5e1eb3a0abeb.

**Comment by Kakise** [comment]
A new update just has been released, it fixes this issue. Update Dyson-local and try again

**Comment by rkallensee** [comment]
Thanks, that was fast! But now running into https://github.com/shenxn/ha-dyson/issues/115. 😅
