### ISSUE TITLE
Cannot setup Dyson 

### ISSUE THREAD

**Issue by haaino** [shenxn/ha-dyson#123]
Since HA 2022.4 I always get this error when I try to install dyson cloud or local

Logger: homeassistant.config_entries
Source: config_entries.py:745 
First occurred: 22:59:14 (4 occurrences) 
Last logged: 23:15:54

Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)
Error occurred loading configuration flow for integration dyson_local: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

In the log file

2022-04-08 23:15:40 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of libdyson==0.8.11
2022-04-08 23:15:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration dyson_local: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

From the UI point of view I get an error message that this integration does not support configuration through a UI

**Comment by GitPetri** [comment]
@haaino please see https://github.com/shenxn/ha-dyson/issues/103#issuecomment-1093872551, I got rid of similar error situation

**Comment by haaino** [comment]
Indeed the behavior has changed. I get a GUI again. 

But when I try to enroll a get an error message when submitting my uid
----
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/dyson_cloud/config_flow.py:71 
Integration: Dyson Cloud (documentation, issues) 
First occurred: 18:11:16 (3 occurrences) 
Last logged: 18:12:08

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 206, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/dyson_cloud/config_flow.py", line 71, in async_step_email
    self._verify = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 122, in login_email_otp
    return response
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 114, in request
    verify=self._CERT,
libdyson.exceptions.DysonInvalidAuth

---

Suggestions ?

**Comment by Kakise** [comment]
> Indeed the behavior has changed. I get a GUI again.
> 
> ## But when I try to enroll a get an error message when submitting my uid
> This error originated from a custom integration.
> 
> Logger: aiohttp.server Source: custom_components/dyson_cloud/config_flow.py:71 Integration: Dyson Cloud (documentation, issues) First occurred: 18:11:16 (3 occurrences) Last logged: 18:12:08
> 
> Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle result = await result File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 206, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper result = await method(view, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step result: FlowResult = await getattr(flow, method)(user_input) File "/config/custom_components/dyson_cloud/config_flow.py", line 71, in async_step_email self._verify = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 122, in login_email_otp return response File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 114, in request verify=self._CERT, libdyson.exceptions.DysonInvalidAuth
> 
> Suggestions ?

Sorry I can't help with Dyson cloud, only Dyson local is being maintained and updated. I'll close this issue as it's related to Dyson cloud and not Dyson local.
