### ISSUE TITLE
Local integration stopped working in HA 2024.1

### ISSUE THREAD

**Issue by EDelsman** [shenxn/ha-dyson#196]
I got an error loading the integration, most likely due to an int being changed to an enumeration in this release:

2024-01-03 21:38:40.071 ERROR (MainThread) [homeassistant.components.humidifier] Error adding entities for domain humidifier with platform dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 217, in state_attributes
    if HumidifierEntityFeature.MODES in self.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
2024-01-03 21:38:40.560 ERROR (MainThread) [homeassistant.components.humidifier] Error while setting up dyson_local platform for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 217, in state_attributes
    if HumidifierEntityFeature.MODES in self.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by Trabbi1999** [comment]
Hi,

I have the Humidifier with the Formaldehyde Filter. My integration loads and is working (partly) but since the update, the humidifier is not available anymore and I get the same errors just like you. Other options are still available and controllable

**Comment by Trabbi1999** [comment]
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation/

I'm not a developer but I found this in the release notes, maybe this correlates with our issue.

**Comment by pguich** [comment]
> Hi,
> 
> I have the Humidifier with the Formaldehyde Filter. My integration loads and is working (partly) but since the update, the humidifier is not available anymore and I get the same errors just like you. Other options are still available and controllable

I have the same issue since today.

**Comment by dotvezz** [comment]
Hi everyone! Please feel free to check out https://github.com/libdyson-wg/ha-dyson. It's a continuation of this repository which has been fixing bugs and adding new devices and compatibility features. It supports Home Assistant 2024 and is also a HACS Default repository: https://my.home-assistant.io/redirect/hacs_repository/?owner=libdyson-wg&repository=ha-dyson&category=integration, so you can install without adding a custom repository to HACS now.

If you have any questions, I'm the core maintainer for the new repo.
