### ISSUE TITLE
API error when sending a dyson_local.set_timer of 0 to cancel timer

### ISSUE THREAD

**Issue by gojojo77** [shenxn/ha-dyson#26]
Thanks for all the work on this integration, it is really great.

I am using v0.6.0 through HACS

There is a small contradiction between the documentation and the API call for 'dyson_local.set_timer'. When you send a value of 0 it produces an error:
```
service: dyson_local.set_timer
data:
  entity_id: fan.master_bedroom
  timer: 0
```
`"ValueError: Duration must be between 1 and 540"`

However the documentation string in Home Assistant says this should be allowed:
"timer | The value in minutes to set the timer to, **0 to disable it**"

I believe values of 0 used to be allowed, to cancel the timer.

Thanks for taking a look. Let me know if you need any further info...

Full log below:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 578, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dyson_local/fan.py", line 163, in set_timer
    self._device.set_sleep_timer(timer)
  File "/usr/local/lib/python3.8/site-packages/libdyson/dyson_device.py", line 394, in set_sleep_timer
    raise ValueError("Duration must be between 1 and 540")
ValueError: Duration must be between 1 and 540
```

**Comment by shenxn** [comment]
Fixed in version 0.6.2
