### ISSUE TITLE
Fan status error in HA 2021.3.4 version

### ISSUE THREAD

**Issue by GwangGyuChoi** [shenxn/ha-dyson#31]
Hello?
I am using a Humidify model, it has been successful without the humidification function.
But, updating HA to 2021.3.4 and updating Dyson Local to 0.8.1 adds a humidification function, but there are problems with the fan's condition and execution.
First, the status information of the fan cannot be obtained, and the on/off is controlled at the speed of the fan, but it is also not stable.
Please review it.

* HA version : 2021.3.4
* Dyson Cloud version : v0.8.0
* Dyson Local version : v0.8.1

* Components : fan.mydyson
* State: unavailable

* Status Properties
restored: true
speed_list:
  - 'off'
  - low
  - medium
  - high
preset_modes: []
supported_features: 3
friendly_name: mydyson

detail logs

1. 
Logger: homeassistant
Source: custom_components/dyson_local/fan.py:255
First occurred: 오후 3:59:31 (77 occurrences)
Last logged: 오후 5:26:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 282, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/dyson_local/fan.py", line 260, in device_state_attributes
    return {ATTR_OSCILLATION_MODE: self.oscillation_mode}
  File "/config/custom_components/dyson_local/fan.py", line 255, in oscillation_mode
    return OSCILLATION_MODE_ENUM_TO_STR[self._device.oscillation_mode]
  File "/usr/local/lib/python3.8/site-packages/libdyson/dyson_pure_humidify_cool.py", line 29, in oscillation_mode
    return HumidifyOscillationMode(self._get_field_value(self._status, "ancp"))
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'CUST' is not a valid HumidifyOscillationMode

 2.
Logger: homeassistant.components.fan
Source: custom_components/dyson_local/fan.py:255
Integration: fan (documentation, issues)
First occurred: 오후 3:51:58 (2 occurrences)
Last logged: 오후 3:52:00

Error adding entities for domain fan with platform dyson_local
Error while setting up dyson_local platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/dyson_local/fan.py", line 260, in device_state_attributes
    return {ATTR_OSCILLATION_MODE: self.oscillation_mode}
  File "/config/custom_components/dyson_local/fan.py", line 255, in oscillation_mode
    return OSCILLATION_MODE_ENUM_TO_STR[self._device.oscillation_mode]
  File "/usr/local/lib/python3.8/site-packages/libdyson/dyson_pure_humidify_cool.py", line 29, in oscillation_mode
    return HumidifyOscillationMode(self._get_field_value(self._status, "ancp"))
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'CUST' is not a valid HumidifyOscillationMode

** Temporary Resolved
I removed and executed the logic of "dyson_local/fan.py" file to solve the problem.
So I did normal action.
However, I don't know how to correct the error.

↓removed code↓

    @property
    def oscillation_mode(self) -> str:
        """Return oscillation mode."""
        return OSCILLATION_MODE_ENUM_TO_STR[self._device.oscillation_mode]
 
    @property
    def device_state_attributes(self) -> dict:
        """Return optional state attributes."""
    return {ATTR_OSCILLATION_MODE: self.oscillation_mode}

**Comment by shenxn** [comment]
Seems to be a missing value in `HumidityOscillationMode`. I'll try to fix.

**Comment by shenxn** [comment]
Try if the latest version fixes your problem.
