### ISSUE TITLE
Dyson Local "failed to connect"

### ISSUE THREAD

**Issue by phrostt** [shenxn/ha-dyson#64]
Core version: 2021.8.7
Supervisor version: 2021.06.8
Running in oracle Virtual Box ubuntu VM.

Integration stopped working, I dont remember the error sadly. I removed the integration, to redo it, thinking something may have messed up. I went through the steps, got my credentials using get_devices.py, but the integration it self keeps giving me Failed to connect error.

**Comment by Robert-815** [comment]
Same thing happening here.

**Comment by BradRose** [comment]
+1 to that. I thought I was going nuts and missing something, but it seems to be a bit wider spread than just me.

**Comment by phrostt** [comment]
> I thought I was experiencing issues, but I just ended up deleting the integration, and re-adding it. Steps I took:
> 
> 1. Remove the Dyson Local integration.
> 2. Log out of the Dyson Link app on a mobile device.
> 3. Sign in on a mobile device.
> 4. Run `get_devices.py`, get the appropriate information.
> 5. Add Dyson Local integration > Custom > insert the credential + IP address.
> 
> Not sure if this will fix your issues, but this is what worked for me as of five minutes ago.

Tried that and just about everything and anything else I could find or read about, nothing seems to work.

**Comment by rodhall** [comment]
Same here. Input correct email and "failed to connect" - no way to fix. Local doesn't work because my Dyson Product relies on bluetooth for Wifi setup. If there is a local Wifi available the SSID and PW are not discoverable.

**Comment by Robert-815** [comment]
FWIW I’m running Home Assistant OS on a Raspberry Pi 3(B?) and attempting to connect to a Dyson Pure Hot+Cool Link. It seems like this issue is across multiple platforms and Dyson products but I thought I’d throw it out there.

**Comment by alanchia67** [comment]
> Same here. Input correct email and "failed to connect" - no way to fix. Local doesn't work because my Dyson Product relies on bluetooth for Wifi setup. If there is a local Wifi available the SSID and PW are not discoverable.

Have you tried to logout from the mobile app, and re-login (key in region, email, password) to wait for authentication code via email? This will trigger Dyson authentication server to wait for this authentication code which is needed in the Dyson Local integration.

**Comment by Robert-815** [comment]
> Have you tried to logout from the mobile app

Wait! Don't do this yet. Dyson authentication servers are undergoing maintenance today until approx. 4:30 PM CST. 

I tried signing out of the app but can't log back in, so I contacted Dyson via chat and this was their response.

**Comment by DrBlackRat** [comment]
Have the same error here, any fix found?

**Comment by Robert-815** [comment]
I was never able to figure it out, and I have been away on travels so I have not been able to continue troubleshooting.

**Comment by mwasylyk** [comment]
I was able to just resolve this issue by entering into a shell in the running docker container, and installed libdyson manually with pip. Since the debug log was showing a completely blank exception it was useless, but I had a feeling that it was related to either the libdyson version/missing the lib all together. So that worked for me.

**Comment by 51av0sh** [comment]
So I have the original super old desk fan (DP01) and I've been having issues with the cloud integration since the latest update. I wanted to try local but I'm on hassOS and can't clone the repo and install python (or couldn't figure out how to). I didn't bother with the wifi setup for the local integration since I assumed there was no wifi ssid on this thing since it's so old. Well I was wrong. I was changing the filter today and noticed a sticker inside that can only be seen after removing the filter. Sure enough I saw the ssid and password. Connected flawlessly. If my DP01 has this option then I assume they all do.

**Comment by mwasylyk** [comment]
@51av0sh 
>If my DP01 has this option then I assume they all do.

Nope. My Pure Cool TP04 does not have the ability to create a WIFI hotspot and the internal sticker is just a Bluetooth pairing pin code. I had to run a packet dump on my Android phone while I was readding the TP04 to my Dyson account with the app, and digging through the pcap leads you to the MQTT connect packet with the credentials of the Dyson device. Those are the credentials you can use to setup the local integration, without using  `get_devices.py` from libdyson, as I was only getting nondescript parsing exceptions when using it to get the credentials of my TP04 through my Dyson account. Most likely the data for my TP04 were being returned correctly or at all by the Dyson API, and caused libdyson to fail to print it to STDOUT. This issue was regarding an error while attempting to enter the Dyson device credentials directly, where as you used the WIFI setup connection method which is completely different and handles setting up the connection and calculating the device credentials for you automatically

**Comment by 51av0sh** [comment]
@mwasylyk 

Gotcha. That's a bummer. Good luck!

**Comment by stepoole** [comment]
@damiano75  thank you very much, really appreciate you sharing this info. I was able to get it setup and running.

**Comment by erd82** [comment]
@stepoole did it work for you without any problems? I am getting this error:
![image](https://user-images.githubusercontent.com/63564291/140193111-9a1215e7-7a66-48d1-85e6-62000418e189.png)

Any idea how to fix it?

**Comment by DrBlackRat** [comment]
@erd82 That's the exact error I'm getting as well! Maybe it has something to do with the Regional Code / that we are trying to use the German server?

**Comment by stepoole** [comment]
@erd82 did you install the requirements.txt ? I had to do that first

**Comment by DrBlackRat** [comment]
@stepoole I do and I get the same error as @erd82 
![image](https://user-images.githubusercontent.com/46327609/140200846-56fdb384-de98-4aab-a195-6c71516ec501.png)

**Comment by erd82** [comment]
@stepoole, yes I installed the packages from requirements.txt. After that I received also this InsecureRequestWarning.
![image](https://user-images.githubusercontent.com/63564291/140280665-5d775b76-e137-45c3-bc94-45d197491a7b.png)

Could it have something to do with the python version (I have 3.10)?

@DrBlackRat, yes I think so that the region could be part of the root cause ... that might also be the reason Dyson Cloud runs into the issue above. In your error log I don't see exactly the same error messages than I have. Did you also install the packages from requirements.txt?

**Comment by DrBlackRat** [comment]
@erd82 Yes, I have it installed. We also have the same error, this bottom part of yours is the same error I get. 
![SmartSelect_20211104-092921_Opera](https://user-images.githubusercontent.com/46327609/140282074-19579d94-675c-444a-8a29-04aa61e7f80e.jpg)

**Comment by erd82** [comment]
@shenxn an idea how we could fix this issue?

**Comment by RosemaryOrchard** [comment]
I already had the Credential from HomeBridge (which works to control the fan), but the same details don't work with this. I just get "Failed to connect" - I'm not seeing any log files which means there's no data I can provide. I also have a Pure Cool with a bluetooth pairing code.

**Comment by erd82** [comment]
@RosemaryOrchard: Die you also try to connect to German server?

**Comment by RosemaryOrchard** [comment]
> @RosemaryOrchard: Die you also try to connect to German server?

I did today, no change!

When I try to connect and check the network logs in FireFox, the response is this:
```json
{
	"type": "form",
	"flow_id": "b02200e2300f45b8bf718a7826743dae",
	"handler": "dyson_local",
	"step_id": "manual",
	"data_schema": [
		{
			"type": "string",
			"name": "serial",
			"required": true,
			"default": "VW1-UK-XXXXX78B"
		},
		{
			"type": "string",
			"name": "credential",
			"required": true,
			"default": "MYCREDENTIALS"
		},
		{
			"type": "select",
			"options": [
				[
					"N223",
					"360 Eye robot vacuum"
				],
				[
					"276",
					"360 Heurist robot vacuum"
				],
				[
					"438",
					"Pure Cool"
				],
				[
					"438E",
					"Pure Cool (2021)"
				],
				[
					"520",
					"Pure Cool Desk"
				],
				[
					"475",
					"Pure Cool Link"
				],
				[
					"469",
					"Pure Cool Link Desk"
				],
				[
					"527",
					"Pure Hot+Cool"
				],
				[
					"527E",
					"Pure Hot+Cool (New)"
				],
				[
					"455",
					"Pure Hot+Cool Link"
				],
				[
					"358",
					"Pure Humidify+Cool"
				]
			],
			"name": "device_type",
			"required": true,
			"default": "520"
		},
		{
			"type": "string",
			"name": "host",
			"optional": true,
			"default": "192.168.4.58"
		}
	],
	"errors": {
		"base": "cannot_connect"
	},
	"description_placeholders": null,
	"last_step": null
}
```

Unfortunately "cannot_connect" does not really tell me a lot, so I'll have to keep digging.

**Comment by RosemaryOrchard** [comment]
I did some further debugging by changing line 258 in config_flow.py to `_LOGGER.debug("Failed to connect to device: %s", err, exc_info=True, stack_info=True)`, and here's the result:

```
2021-11-17 00:15:53 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Device: <libdyson.dyson_pure_cool_link.DysonPureCoolLink object at 0x7f922766a0>
2021-11-17 00:15:53 DEBUG (Thread-10) [libdyson.dyson_device] Connected with result code 5
2021-11-17 00:15:53 DEBUG (Thread-10) [libdyson.dyson_device] Disconnected with result code 0
2021-11-17 00:15:53 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device:
Traceback (most recent call last):
File "/config/custom_components/dyson_local/config_flow.py", line 259, in _async_try_connect
device.connect(host)
File "/usr/local/lib/python3.9/site-packages/libdyson/dyson_device.py", line 104, in connect
raise error
libdyson.exceptions.DysonConnectionRefused
Stack (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/src/homeassistant/homeassistant/__main__.py", line 331, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 318, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 121, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
self._run_once()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
handle._run()
File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/dyson_local/config_flow.py", line 125, in async_step_manual
data = await self._async_get_entry_data(
File "/config/custom_components/dyson_local/config_flow.py", line 216, in _async_get_entry_data
await self._async_try_connect(serial, credential, device_type, host)
File "/config/custom_components/dyson_local/config_flow.py", line 263, in _async_try_connect
_LOGGER.debug("Failed to connect to device: %s", err, exc_info=True, stack_info=True)
Stack (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/src/homeassistant/homeassistant/__main__.py", line 331, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 318, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 121, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
self._run_once()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
handle._run()
File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/dyson_local/config_flow.py", line 125, in async_step_manual
data = await self._async_get_entry_data(
File "/config/custom_components/dyson_local/config_flow.py", line 216, in _async_get_entry_data
await self._async_try_connect(serial, credential, device_type, host)
File "/config/custom_components/dyson_local/config_flow.py", line 263, in _async_try_connect
_LOGGER.debug("Failed to connect to device: %s", err, exc_info=True, stack_info=True)
2021-11-17 00:16:04 INFO (SyncWorker_0) [pychromecast] Querying device status
```

Sadly I'm not a Python dev so I'm not sure where to go from here, but I hope this helps.

**Comment by bennyb0i** [comment]
> @stepoole did it work for you without any problems? I am getting this error: ![image](https://user-images.githubusercontent.com/63564291/140193111-9a1215e7-7a66-48d1-85e6-62000418e189.png)
> 
> Any idea how to fix it?

Didn't see if this was ever addressed, but the issue was solved for me by logging out of the mobile app and then re-running the python script. It'll then prompt you for your account password and the verification code sent to your email.

**Comment by Kakise** [comment]
See #66
