### ISSUE TITLE
Unavailable after HASS reboot

### ISSUE THREAD

**Issue by MJHeijster** [shenxn/ha-dyson#98]
I have a Dyson Pure Cool Link 2016 connected to Home Assistant through this integration and after a Home Assistant reboot, the device is showing as unavailable. After power cycling the fan, everything comes back online. Is anyone else experiencing this? 

The only logging that seemed relevant was:
2022-02-03 09:59:27 ERROR (zeroconf-ServiceBrowser-_dyson_mqtt._tcp-_360eye_mqtt._tcp-275) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 532, in run
    self._fire_service_state_changed_event(event)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 416, in _fire_service_state_changed_event
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/__init__.py", line 55, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 177, in on_change
    getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
  File "/usr/local/lib/python3.9/site-packages/libdyson/discovery.py", line 81, in add_service
    self._dyson_discovery.device_discovered(info)
  File "/usr/local/lib/python3.9/site-packages/libdyson/discovery.py", line 37, in device_discovered
    if info.type == TYPE_DYSON_360_EYE:
AttributeError: 'NoneType' object has no attribute 'type'

**Comment by engloy** [comment]
What do you mean by power cycle? I tried turning the fan on and off and unplugging it and replugging but nothing seems to work

**Comment by MJHeijster** [comment]
> What do you mean by power cycle? I tried turning the fan on and off and unplugging it and replugging but nothing seems to work

A power cycle is turning it off, waiting a while and plugging it back in. If it still doesn't work for you and it used to work, it seems like you have a different issue :(

**Comment by engloy** [comment]
> > What do you mean by power cycle? I tried turning the fan on and off and unplugging it and replugging but nothing seems to work
> 
> A power cycle is turning it off, waiting a while and plugging it back in. If it still doesn't work for you and it used to work, it seems like you have a different issue :(

Thanks! It worked with your advice.
