### ISSUE TITLE
"Unknown Error Occurred"

### ISSUE THREAD

**Issue by notkvnchn** [shenxn/ha-dyson#99]
tried to set up the cloud version, enter my email and an "unknown error" occurs every time.

**Comment by gazzmundo** [comment]
I'm getting exactly the same error when trying to use get_devices.py, but after the verification code stage.

For me, I can successfully enter my password and generate a code by email. After entering the verification code, I then get the DysonInvalidAuth error:

Please choose your account region
Region code: GB
Email: <email>
Password: <password>
Verification code: <code>
Traceback (most recent call last):
  File "C:\libdyson\libdyson\libdyson-main\get_devices.py", line 25, in <module>
    verify(otp, password)
  File "C:\libdyson\libdyson\libdyson-main\libdyson\cloud\account.py", line 147, in _verify
    response = self.request(
  File "C:\libdyson\libdyson\libdyson-main\libdyson\cloud\account.py", line 114, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth

**Comment by jchhenderson** [comment]
OK, so this worked for me after logging out and then back in of the Dyson app on my phone.
